### PR TITLE
Fixed pthreads and release build.

### PR DESCRIPTION
**Pull request by Garey27**
- Made actually link pthread
- Fixed a release build was always being compiled as debug

### CODE REVIEW

**Comment by wopox1337** [comment]
FIX: #2

**Comment by ShootingKing-AM** [comment]
Did you test the auto build's .so guys ?? :D

**Comment by wopox1337** [comment]
@ShootingKing-AM auto-build only on maser branch...
https://github.com/ShootingKing-AM/ThreadedSockets/blob/master/appveyor.yml#L4-L6

**Comment by ShootingKing-AM** [comment]
No no, Auto Build + Deploy is for master branch. PRs are also auto build, but not deployed. You can find PR Builds in AppVeyor History [here](https://ci.appveyor.com/project/ShootingKing-AM/threadedsockets/builds/36479919). And Artifacts(binary files) for Linux [Release](https://ci.appveyor.com/project/ShootingKing-AM/threadedsockets/builds/36479919/job/ak87gs93d2de7we5/artifacts) & [Debug](https://ci.appveyor.com/project/ShootingKing-AM/threadedsockets/builds/36479919/job/3liqwc7xw2p1bhs9/artifacts).

And about the **Release Project**, uploading **Debug build** was done because at that time **Release build** was not working as intenteded on Linux.

Let me say again, but the binaries **v1.1** are still working fine for me on Ubuntu 20 LTS, idk why they are not working on your setup.

I actually tried appending -lpthread in 306c5f87992403ad7b76f3d5f7eb1af344b545cd Commit(its build is [here](https://ci.appveyor.com/project/ShootingKing-AM/threadedsockets/builds/36466020)), but i could not get it to load on Ubuntu, which is weird ^^'

I cannot load the module.so.zip you uploaded in Issue #2 @wopox1337. Getting a Bad load, mysetup is,

```
amxx modules
Currently loaded modules:
      name                    version     author               status     
 [ 1] Fun                     1.8.2       AMX Mod X Dev Team   running    
 [ 2] unknown                 unknown     unknown              bad load   
 [ 3] CStrike                 1.8.2       AMX Mod X Dev Team   running    
 [ 4] CSX                     1.8.2       AMX Mod X Dev Team   running    
4 modules, 3 correct

amxx version
AMX Mod X 1.8.2 (http://www.amxmodx.org)
Authors:
	David "BAILOPAN" Anderson, Pavol "PM OnoTo" Marko
	Felix "SniperBeamer" Geyer, Jonny "Got His Gun" Bergstrom
	Lukasz "SidLuke" Wlasinski, Christian "Basic-Master" Hammacher
	Borja "faluco" Ferrer, Scott "DS" Ehlert
Compiled: Feb 14 2013, 00:55:09
Build ID: 1.8.2 61:2ae84f7c0a97
Core mode: JIT ASM32

meta list
Currently loaded plugins:
      description      stat pend  file              vers      src  load  unlod
 [ 1] AMX Mod X        RUN   -    amxmodx_mm_i386.  v1.8.2    ini  Start ANY  
 [ 2] Fun              RUN   -    fun_amxx_i386.so  v1.8.2    pl1  ANY   ANY  
 [ 3] CStrike          RUN   -    cstrike_amxx_i38  v1.8.2    pl1  ANY   ANY  
 [ 4] CSX              RUN   -    csx_amxx_i386.so  v1.8.2    pl1  ANY   ANY  
4 plugins, 4 running

meta version
Metamod v1.21.1-am  2013-09-26 (5:13)
by Will Day <willday@metamod.org>
   http://www.metamod.org/
compiled: Sep 26 2013, 17:09:41 -0500 (optimized)

version
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 19:52:19 Aug  3 2020 (8684)

meta load addons/amxmodx/modules/sockets_amxx_i386.so 
L 11/24/2020 - 12:50:06: [META] (debug:2) Resolved 'addons/amxmodx/modules/sockets_amxx_i386.so' to file '/home/ubuntu/.steam/steamapps/common/Half-Life/cstrike/addons/amxmodx/modules/sockets_amxx_i386.so'
L 11/24/2020 - 12:50:06: [META] ERROR: dll: Failed query plugin '<sockets_amxx_i386.so>'; Couldn't open file '/home/ubuntu/.steam/steamapps/common/Half-Life/cstrike/addons/amxmodx/modules/sockets_amxx_i386.so': /home/ubuntu/.steam/steamapps/common/Half-Life/cstrike/addons/amxmodx/modules/sockets_amxx_i386.so: undefined symbol: _ZdlPvj
L 11/24/2020 - 12:50:06: [META] ERROR: dll: Skipping plugin '<sockets_amxx_i386.so>'; couldn't query
Couldn't load plugin '<sockets_amxx_i386.so>'; see log
Currently loaded plugins:
      description      stat pend  file              vers      src  load  unlod
 [ 1] AMX Mod X        RUN   -    amxmodx_mm_i386.  v1.8.2    ini  Start ANY  
 [ 2] Fun              RUN   -    fun_amxx_i386.so  v1.8.2    pl1  ANY   ANY  
 [ 3] CStrike          RUN   -    cstrike_amxx_i38  v1.8.2    pl1  ANY   ANY  
 [ 4] CSX              RUN   -    csx_amxx_i386.so  v1.8.2    pl1  ANY   ANY  
 [ 5] <sockets_amxx_i  badf load  sockets_amxx_i38  v -       cmd   -     -   
5 plugins, 4 running
```
System Setup
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

Operating System: Ubuntu 20.04.1 LTS
Kernel: Linux 5.4.0-42-generic
Architecture: x86-64
```

**Comment by wopox1337** [comment]
we didn't test the auto-build.

**Comment by ShootingKing-AM** [comment]
I could not load your built module, detailed updated in previous comment. You can test and get back with results, i think we are hitting the wrong cause.

**Comment by wopox1337** [comment]
So strange

**Comment by ShootingKing-AM** [comment]
So did you guys test auto-build on your setups ?

**Comment by afwn90cj93201nixr2e1re** [comment]
I'll take a look, np.

**Comment by afwn90cj93201nixr2e1re** [comment]
Em, and why are u attaching pthreads withot dl?

**Comment by ShootingKing-AM** [comment]
This fix is not working on supported version of Amxmodx 1.8 and Metamod-AM.

**Pull request closed without merging**
